VERSION 0.8
FROM --pass-args ..+base

IMPORT .. AS tests

WORKDIR /test

test-all:
    DO tests+RUN_EARTHLY --earthfile=manifest.earth --target=+gha
    RUN if ! grep -q '^::group::' earthly.output; then echo "::group:: not found"; exit 1; fi
    RUN if grep -q '^should have prefix' earthly.output; then echo "Error: Line starts with 'should have prefix'"; exit 1; fi
    RUN if ! grep -q '^::endgroup::' earthly.output; then echo "::endgroup:: not found"; exit 1; fi
