VERSION 0.5
FROM alpine:3.13

mysubimage:
    WORKDIR /data
    RUN echo a532d715-bd5a-448a-917f-b5ec4996b22c > mysubimage
    SAVE IMAGE mysubimage:fromtest

myimage:
    FROM +mysubimage
    RUN echo 1222dca7-f95d-4854-89c5-d4762e372c59 > myimage
    SAVE IMAGE myimage:fromtest
