FROM earthly/dind
WORKDIR /test

all:
    BUILD \
        --build-arg INDEX=1 \
        --build-arg INDEX=2 \
        --build-arg INDEX=3 \
        --build-arg INDEX=4 \
        --build-arg INDEX=5 \
        +test

print-countries:
    FROM jbergknoff/postgresql-client:latest
    CMD ["-c", "SELECT * FROM country WHERE country_id = '76'"]

test:
    RUN apk add postgresql-client
    COPY docker-compose.yml .
    # Index is used to create parallel tests.
    ARG INDEX=0
    WITH DOCKER \
            --compose docker-compose.yml \
            --service postgres \
            --load print-countries:latest=+print-countries
        RUN while ! pg_isready --host=localhost --port=5432 --dbname=iso3166 --username=postgres; do sleep 1; done ;\
            docker-compose up --exit-code-from print-countries print-countries | grep Brazil
    END
