VERSION 0.5
FROM alpine:3.13

mysubimage:
    WORKDIR /data
    RUN echo 88b383e9-4222-4a82-b767-79229a35aa21 > mysubimage-data
    SAVE ARTIFACT mysubimage-data
    SAVE IMAGE mysubimage:copytest

myimage:
    COPY +mysubimage/mysubimage-data .
    RUN echo b3a2dfc1-e4fb-4904-bfb0-15bdce9fe2db > myimage
    SAVE IMAGE myimage:copytest
