VERSION --wait-block 0.6
# This is the fixed version (using wait-block)
test-case:
  FROM debian
  ARG EARTHLY_PUSH
  RUN --push mkdir -p artifact
  SAVE ARTIFACT artifact AS LOCAL test-output/artifact

