deps:
    FROM centos:8.3.2011
    RUN yum install -y createrepo rpm-build wget

rpm:
    ARG EARTHLY_VERSION
    FROM +deps
    WORKDIR /work
    RUN echo "$EARTHLY_VERSION" | grep '^[0-9]\+.[0-9]\+.[0-9]\+$' # ensure version is of the form 1.2.3
    RUN wget -q "https://github.com/earthly/earthly/releases/download/v${EARTHLY_VERSION}/earthly-linux-amd64" -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly
    COPY earthly.spec .
    RUN sed -i "s/__earthly_version__/$EARTHLY_VERSION/" earthly.spec
    RUN cat earthly.spec
    RUN rpmbuild --target x86_64 -bb earthly.spec
    SAVE ARTIFACT "/root/rpmbuild/RPMS/x86_64/earthly-${EARTHLY_VERSION}-1.x86_64.rpm" AS LOCAL "earthly-${EARTHLY_VERSION}-1.x86_64.rpm"

test-rpm:
    ARG EARTHLY_VERSION
    FROM centos:8.3.2011
    COPY +rpm/earthly-${EARTHLY_VERSION}-1.x86_64.rpm .
    RUN yum localinstall -y earthly-${EARTHLY_VERSION}-1.x86_64.rpm && earthly --version

yum-repo:
    ARG EARTHLY_VERSION
    FROM +deps
    WORKDIR /repo
    COPY --build-arg EARTHLY_VERSION +rpm/earthly-${EARTHLY_VERSION}-1.x86_64.rpm .
    RUN createrepo .
    SAVE ARTIFACT /repo AS LOCAL repo

yum-repo-server:
    FROM python:3
    RUN mkdir -p /repo-data/CentOS/8/os/x86_64
    COPY +yum-repo/repo /repo-data/CentOS/8/os/x86_64
    CMD python -m http.server --directory /repo-data 8000

yum-repo-tester:
    FROM +deps
    RUN yum install -y curl

    RUN echo "[earthly-test]" > /etc/yum.repos.d/earthly-test.repo
    RUN echo "name=Earthly Test Repository" >> /etc/yum.repos.d/earthly-test.repo
    RUN echo "baseurl=http://127.0.0.1:8000/CentOS/8/os/x86_64/" >> /etc/yum.repos.d/earthly-test.repo
    RUN echo "enabled=1" >> /etc/yum.repos.d/earthly-test.repo
    RUN echo "gpgcheck=0" >> /etc/yum.repos.d/earthly-test.repo # TODO setup gpg signing

    RUN echo "[earthly-test]
name=Earthly Test Repository
baseurl=http://127.0.0.1:8000/CentOS/8/os/x86_64/
enabled=1
gpgcheck=0" > /etc/yum.repos.d/earthly-test.repo # TODO setup gpg signing

test-repo:
    ARG EARTHLY_VERSION
    FROM earthly/dind:alpine
    RUN apk add curl
    WITH DOCKER \
        --load yum:server=+yum-repo-server \
        --load yum:tester=+yum-repo-tester
        RUN docker run -d --network=host yum:server \
            && sleep 1 \
            && docker run --network=host yum:tester /bin/sh -c "yum install -y earthly && earthly --version | grep 'earthly version v$EARTHLY_VERSION linux/amd64'"
    END

test:
    ARG EARTHLY_VERSION=0.5.3
    BUILD --build-arg EARTHLY_VERSION +test-repo
