root: ./docs/

structure:
    readme: README.md
    summary: SUMMARY.md

redirects:
    earth-command: earthly-command/earthly-command.md
    earth-config: earthly-config/earthly-config.md
    installation: ./README.md
    guides/pushing-and-pulling-images-with-cloud-providers: guides/configuring-registries
    guides/pushing-and-pulling-images-with-cloud-providers/pushing-images-to-ecr: guides/configuring-registries/aws-ecr.md
    guides/pushing-and-pulling-images-with-cloud-providers/pushing-images-to-gcr: guides/configuring-registries/gcp-artifact-registry.md
    guides/pushing-and-pulling-images-with-cloud-providers/pushing-images-to-acr: guides/configuring-registries/azure-acr.md
