root: ./docs/

structure:
    readme: README.md
    summary: SUMMARY.md

redirects:
    earthfile: earthfile/earthfile.md
    the-earthly-command/earthly-command: earthly-command/earthly-command.md
    guides: ./README.md
    guides/advanced-local-caching: caching/caching-in-earthfiles.md
    docs/guides/advanced-local-caching: caching/caching-in-earthfiles.md
    guides/auth: guides/auth.md
    guides/cache: caching/managing-cache.md
    docs/guides/cache: caching/managing-cache.md
    docs/guides/cloud-secrets: cloud/cloud-secrets.md
    guides/cloud-secrets: cloud/cloud-secrets.md
    guides/debugging: guides/debugging.md
    guides/docker-in-earthly: guides/docker-in-earthly.md
    guides/integration: guides/integration.md
    guides/multi-platform: guides/multi-platform.md
    guides/target-ref: guides/importing.md
    docs/guides/target-ref: guides/importing.md
    guides/udc: guides/functions.md
    docs/guides/udc: guides/functions.md
    earthly-config: earthly-config/earthly-config.md
    ci-integration: ci-integration/overview.md
    earth-command: earthly-command/earthly-command.md
    earth-config: earthly-config/earthly-config.md
    installation: ./README.md
    guides/pushing-and-pulling-images-with-cloud-providers: guides/auth.md
    guides/pushing-and-pulling-images-with-cloud-providers/pushing-images-to-ecr: guides/registries/aws-ecr.md
    guides/pushing-and-pulling-images-with-cloud-providers/pushing-images-to-gcr: guides/registries/gcp-artifact-registry.md
    guides/pushing-and-pulling-images-with-cloud-providers/pushing-images-to-acr: guides/registries/azure-acr.md
    guides/configuring-registries/aws-ecr: guides/registries/aws-ecr.md
    guides/configuring-registries/azure-acr: guides/registries/azure-acr.md
    guides/configuring-registries/gcp-artifact-registry: guides/registries/gcp-artifact-registry.md
    guides/configuring-registries/self-signed: guides/registries/self-signed.md
    examples/gh-actions-integration: ci-integration/guides/gh-actions-integration.md
    examples/circle-integration: ci-integration/guides/circle-integration.md
    examples/codebuild-integration: ci-integration/guides/codebuild-integration.md
    examples/kubernetes: ci-integration/guides/kubernetes.md
    examples/jenkins: ci-integration/guides/jenkins.md
    alt-installation: alt-installation/alt-installation.md
    guides/basics: basics/basics.md
    basics: basics/basics.md
    best-practices: guides/best-practices.md
    guides/ci-integration: ci-integration/overview.md
    docs/ci-integration: ci-integration/overview.md
    ci-examples/ci-examples: ci-integration/overview.md
    examples/examples: examples/examples.md
    examples/ci-examples: ci-integration/overview.md
    examples/ci-examples/gh-actions-integration: ci-integration/guides/gh-actions-integration.md
    examples/ci-examples/circle-integration: ci-integration/guides/circle-integration.md
    examples/ci-examples/codebuild-integration: ci-integration/guides/codebuild-integration.md
    ci-examples/gh-actions-integration: ci-integration/guides/gh-actions-integration.md
    ci-examples/circle-integration: ci-integration/guides/circle-integration.md
    ci-examples/codebuild-integration: ci-integration/guides/codebuild-integration.md
    basics/part-2-executing-a-build: basics/part-2-running-the-build.md
    basics/part-3-detailed-explanation: basics/part-1b-detailed-explanation.md
    basics/part-4-adding-dependencies-in-the-mix: basics/part-3-adding-dependencies.md
    basics/part-6-reduce-code-duplication: basics/part-5-reducing-code-duplication.md
    basics/part-2-detailed-explanation: basics/part-1b-detailed-explanation.md
    basics/part-3-adding-dependencies-in-the-mix: basics/part-3-adding-dependencies.md
    basics/part-4-efficient-caching-of-dependencies: basics/part-4-caching-dependencies.md
    basics/part-5-reduce-code-duplication: basics/part-5-reducing-code-duplication.md
    examples/go: examples/examples.md
    examples/other-earthfile-examples: examples/examples.md
    examples/other-earthfile-examples/earthly: examples/examples.md
    examples/other-earthfile-examples/monorepo: examples/examples.md
    examples/other-earthfile-examples/multirepo: examples/examples.md
    examples/per-language-earthfile-examples: examples/examples.md
    examples/per-language-earthfile-examples/cpp: examples/examples.md
    examples/per-language-earthfile-examples/go: examples/examples.md
    examples/per-language-earthfile-examples/java: examples/examples.md
    examples/per-language-earthfile-examples/js: examples/examples.md
    examples/per-language-earthfile-examples/python: examples/examples.md
    guides/configuring-registries: guides/auth.md
    guides/shared-cache: ./caching/caching-via-registry.md
    docs/remote-caching: ./caching/caching-via-registry.md
    earthly-cloud/satellites: cloud/satellites.md
