root: ./docs/

structure:
    readme: README.md
    summary: SUMMARY.md

redirects:
    earth-command: earthly-command/earthly-command.md
    earth-config: earthly-config/earthly-config.md
    installation: alt-installation/alt-installation.md
