root: ./docs/

structure:
    readme: README.md
    summary: SUMMARY.md

redirects:
    earthfile: earthfile/earthfile.md
    the-earthly-command/earthly-command: earthly-command/earthly-command.md
    guides: docs/guides
    guides/advanced-local-caching: guides/advanced-local-caching.md
    guides/auth: guides/auth.md
    guides/cache: guides/cache.md
    guides/cloud-secrets: guides/cloud-secrets.md
    guides/debugging: guides/debugging.md
    guides/docker-in-earthly: guides/docker-in-earthly.md
    guides/integration: guides/integration.md
    guides/multi-platform: guides/multi-platform.md
    guides/shared-cache: guides/shared-cache.md
    guides/target-ref: guides/target-ref.md
    guides/udc: guides/udc.md
    earthly-config: earthly-config/earthly-config.md
    ci-integration: ci-integration.md
    earth-command: earthly-command/earthly-command.md
    earth-config: earthly-config/earthly-config.md
    installation: ./README.md
    guides/pushing-and-pulling-images-with-cloud-providers: guides/configuring-registries
    guides/pushing-and-pulling-images-with-cloud-providers/pushing-images-to-ecr: guides/configuring-registries/aws-ecr.md
    guides/pushing-and-pulling-images-with-cloud-providers/pushing-images-to-gcr: guides/configuring-registries/gcp-artifact-registry.md
    guides/pushing-and-pulling-images-with-cloud-providers/pushing-images-to-acr: guides/configuring-registries/azure-acr.md
    guides/configuring-registries/aws-ecr: guides/configuring-registries/aws-ecr.md
    guides/configuring-registries/gcp-artifact-registry: guides/configuring-registries/gcp-artifact-registry.md
    guides/configuring-registries/azure-acr: guides/configuring-registries/azure-acr.md
    examples/gh-actions-integration: ci-integration/guides/gh-actions-integration.md
    examples/circle-integration: ci-integration/guides/circle-integration.md
    examples/codebuild-integration: ci-integration/guides/codebuild-integration.md
    examples/kubernetes: ci-integration/guides/kubernetes.md
    examples/jenkins: ci-integration/guides/jenkins.md
    alt-installation: alt-installation.md
    guides/basics: basics/basics.md
    basics: basics/basics.md
    guides/ci-integration: ci-integration/overview.md
    examples/examples: examples/examples.md
    examples/ci-examples: ci-integration/vendor-specific-guides
