root: ./docs/

structure:
    readme: README.md
    summary: SUMMARY.md

redirects:
    earth-command: earthly-command/earthly-command.md
    earth-config: earthly-config/earthly-config.md
    installation: https://earthly.dev/get-earthly
