#!/bin/bash
set -e

bindir="$HOME/.earthly"
if [ ! -d "$bindir" ]; then
  mkdir -p "$bindir"
fi

last_check_state_path=/tmp/last-earthly-prerelease-check

get_latest_binary() {
    docker rm --force earthly_binary 2>/dev/null || true

    docker pull earthly/buildkitd:prerelease
    docker pull earthly/earthlybinaries:prerelease
    docker create --name earthly_binary earthly/earthlybinaries:prerelease

    earth_bin_path=/earthly-linux-amd64
    if [ "$(uname)" == "Darwin" ]; then
        earth_bin_path=/earthly-darwin-amd64
    fi

    docker cp earthly_binary:"$earth_bin_path" "$bindir/earthly-prerelease"
    docker rm earthly_binary
}

do_reset() {
    rm -f "$last_check_state_path"
    docker stop earthly-buildkitd || true
    docker rm -f earthly-buildkitd || true
    rm -f "$bindir/earthly-prerelease"
    docker rm --force earthly_binary 2>/dev/null || true
    docker rmi -f earthly/buildkitd:prerelease || true
    docker rmi -f earthly/earthlybinaries:prerelease || true
}

case "$1" in
    reset)
        do_reset
        ;;
    
    *)
        last=$(cat "$last_check_state_path" 2>/dev/null || echo 0)
        now=$(date +%s)
        since=$(( now - last ))

        if [ "$since" -ge 3600 ] && [ -z "$COMP_LINE" ]; then
            echo checking for latest earth pre-release binaries
            get_latest_binary
            echo "Updated prerelease binary. Version:"
            "$bindir/earthly-prerelease" --version
            echo "$now" >"$last_check_state_path"
        fi

        "$bindir/earthly-prerelease" "$@"
        ;;
esac
