FROM ubuntu:20.10

## for apt to be noninteractive
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

RUN apt-get update && apt-get install -y build-essential cmake

WORKDIR /code

code:
  COPY src src
  SAVE IMAGE

build:
  FROM +code
  RUN cmake src
  # cache cmake temp files to prevent rebuilding .o files
  # when the .c files don't change
  RUN --mount=type=cache,target=/code/CMakeFiles make
  SAVE ARTIFACT sum AS LOCAL "sum"

docker:
  COPY +build/sum /bin/sum
  ENTRYPOINT ["/bin/sum"]
  SAVE IMAGE c-example:latest