VERSION --pass-args 0.7

FROM --pass-args ../..+earthly-integration-test-base

IMPORT .. AS tests

WORKDIR /test

test-all:
    BUILD +test-auto-skip
    BUILD +test-auto-skip-with-subdir
    BUILD +test-auto-skip-requires-project
    BUILD +test-auto-skip-wait
    BUILD +test-auto-skip-if-else
    BUILD +test-auto-skip-for-in
    BUILD +test-auto-skip-copy-glob

test-auto-skip:
    RUN echo hello > my-file
    DO --pass-args +RUN_EARTHLY_ARGS --earthfile=simple.earth --target=+mypipeline --output_contains="I was run"
    RUN if ! grep "SSB3YXMgcnVuCg" earthly.output >/dev/null; then echo "base64 encoded RUN echo command is missing from output" && exit 1; fi

    DO --pass-args +RUN_EARTHLY_ARGS --earthfile=simple.earth --target=+mypipeline --output_does_not_contain="I was run"
    RUN if grep "SSB3YXMgcnVuCg" earthly.output >/dev/null; then echo "base64 encoded RUN echo command should not have been displayed" && exit 1; fi

    # change the input file, and validate it runs
    RUN echo world > my-file
    DO --pass-args +RUN_EARTHLY_ARGS --earthfile=simple.earth --target=+mypipeline --output_contains="I was run"
    RUN if ! grep "SSB3YXMgcnVuCg" earthly.output >/dev/null; then echo "base64 encoded RUN echo command is missing from output" && exit 1; fi

test-auto-skip-with-subdir:
    COPY subdir.earth Earthfile
    RUN mkdir subdir
    COPY subdir/test.earth subdir/Earthfile
    RUN echo abc > subdir/a-test-file
    DO --pass-args +RUN_EARTHLY_ARGS --target=+allpipe --output_contains="0bee89b07a248e27c83fc3d5951213c1"
    DO --pass-args +RUN_EARTHLY_ARGS --target=+allpipe --output_does_not_contain="0bee89b07a248e27c83fc3d5951213c1" --output_contains="target .* has already been run; exiting"

    RUN echo 123 > subdir/a-test-file
    DO --pass-args +RUN_EARTHLY_ARGS --target=+allpipe --output_contains="ba1f2511fc30423bdbb183fe33f3dd0f"
    DO --pass-args +RUN_EARTHLY_ARGS --target=+allpipe --output_does_not_contain="ba1f2511fc30423bdbb183fe33f3dd0f" --output_contains="target .* has already been run; exiting"

test-auto-skip-requires-project:
    RUN echo hello > my-file
    DO --pass-args +RUN_EARTHLY_ARGS --earthfile=no-project.earth --target=+no-project --output_contains="I was run"
    RUN if ! grep "PROJECT command missing" earthly.output >/dev/null; then echo "no warning displayed for missing PROJECT keyword" && exit 1; fi

test-auto-skip-wait:
    DO --pass-args +RUN_EARTHLY_ARGS --earthfile=wait.earth --target=+test --output_contains="not skipped"
    DO --pass-args +RUN_EARTHLY_ARGS --earthfile=wait.earth --target=+test --output_contains="8be037baa7b4d09a8e2a37f74154d319d64c996a"

test-auto-skip-if-else:
    DO --pass-args +RUN_EARTHLY_ARGS --earthfile=if-else.earth --target=+test --output_contains="condition ok"
    DO --pass-args +RUN_EARTHLY_ARGS --earthfile=if-else.earth --target=+test --output_contains="40f57fc7955914f3a954c6bd9a2ebe48d0b14f40"

test-auto-skip-for-in:
    DO --pass-args +RUN_EARTHLY_ARGS --earthfile=for.earth --target=+test --output_contains="hello 3"
    DO --pass-args +RUN_EARTHLY_ARGS --earthfile=for.earth --target=+test --output_contains="3d7d7fec7efc5a746e9ac658160427decbf58a0b"

test-auto-skip-copy-glob:
    DO --pass-args +RUN_EARTHLY_ARGS --earthfile=copy-glob.earth --should_fail=true --target=+globstar --output_contains="globstar (\*\*) not supported"

    COPY --dir glob .

    DO --pass-args +RUN_EARTHLY_ARGS --earthfile=copy-glob.earth --target=+dir --output_contains="glob/subdir/hello.txt"
    DO --pass-args +RUN_EARTHLY_ARGS --earthfile=copy-glob.earth --target=+dir --output_contains="a83a5670547528d9e1fd9d1333211c2a0be31749"

    DO --pass-args +RUN_EARTHLY_ARGS --earthfile=copy-glob.earth --target=+glob --output_contains="glob/subdir/hello.txt"
    DO --pass-args +RUN_EARTHLY_ARGS --earthfile=copy-glob.earth --target=+glob --output_contains="5680096677c0bdd4274abcbf81ed160dd199b2bc"

    DO --pass-args +RUN_EARTHLY_ARGS --earthfile=copy-glob.earth --target=+glob-mid-path --output_contains="glob/subdir/hello.txt"
    DO --pass-args +RUN_EARTHLY_ARGS --earthfile=copy-glob.earth --target=+glob-mid-path --output_contains="454f0e07c82fe2dbbc8a28a44074cc541e3d0315"

    DO --pass-args +RUN_EARTHLY_ARGS --earthfile=copy-glob.earth --target=+glob-dir --output_contains="glob/subdir/hello.txt"
    DO --pass-args +RUN_EARTHLY_ARGS --earthfile=copy-glob.earth --target=+glob-dir --output_contains="cf017730f6edfaabc71df9cdc05038f7b66e0dae"

    RUN echo data > glob/subdir/new.txt
    DO --pass-args +RUN_EARTHLY_ARGS --earthfile=copy-glob.earth --target=+glob-dir --output_contains="glob/subdir/new.txt"

test-invalid:
    COPY glob/*/hello.txt /
    RUN --no-cache ls -l /

RUN_EARTHLY_ARGS:
    COMMAND
    ARG earthfile
    ARG target
    ARG should_fail=false
    ARG output_contains
    ARG output_does_not_contain
    DO --pass-args tests+RUN_EARTHLY \
        --earthfile=$earthfile \
        --target=$target \
        --should_fail=$should_fail \
        --output_contains=$output_contains \
        --output_does_not_contain=$output_does_not_contain \
        --extra_args="--auto-skip --auto-skip-db-path=test.db"
