VERSION 0.6

IMPORT .. AS tests

ARG DOCKERHUB_USER_SECRET=+secrets/DOCKERHUB_USER
ARG DOCKERHUB_TOKEN_SECRET=+secrets/DOCKERHUB_TOKEN
ARG DOCKERHUB_MIRROR
ARG DOCKERHUB_AUTH=true
FROM ../..+earthly-integration-test-base \
    --DOCKERHUB_AUTH=$DOCKERHUB_AUTH \
    --DOCKERHUB_USER_SECRET=$DOCKERHUB_USER_SECRET \
    --DOCKERHUB_TOKEN_SECRET=$DOCKERHUB_TOKEN_SECRET \
    --DOCKERHUB_MIRROR=$DOCKERHUB_MIRROR

RUN apk add --update --no-cache \
    perl findutils

WORKDIR /test

all:
    BUILD +udc
    BUILD +var-arg
    BUILD +platform

udc:
    DO +RUN_EARTHLY_ARGS --earthfile=udc.earth --target=+images --extra_args="--no-output"

var-arg:
    DO +RUN_EARTHLY_ARGS --earthfile=var-arg.earth --target=+all --extra_args="--no-output"

platform:
    DO +RUN_EARTHLY_ARGS --earthfile=platform.earth --target=+images --extra_args="--no-output"

RUN_EARTHLY_ARGS:
    COMMAND
    ARG earthfile
    ARG target
    ARG should_fail=false
    ARG extra_args
    DO tests+RUN_EARTHLY \
        --earthfile=$earthfile \
        --target=$target \
        --should_fail=$should_fail \
        --extra_args=$extra_args \
        --DOCKERHUB_AUTH=$DOCKERHUB_AUTH \
        --DOCKERHUB_USER_SECRET=$DOCKERHUB_USER_SECRET \
        --DOCKERHUB_TOKEN_SECRET=$DOCKERHUB_TOKEN_SECRET \
        --DOCKERHUB_MIRROR=$DOCKERHUB_MIRROR
