ARG DOCKERHUB_AUTH=true
FROM ../../..+earthly-integration-test-base --DOCKERHUB_AUTH=$DOCKERHUB_AUTH

IMPORT .. AS tests

WORKDIR /test

test-single-line:
    DO tests+RUN_EARTHLY --earthfile=single-line.earth --target=+test

test-single-line-with-args:
    DO tests+RUN_EARTHLY --earthfile=single-line-with-args.earth --target=+test

test-single-line-with-comment:
    DO tests+RUN_EARTHLY --earthfile=single-line-with-comment.earth --target=+test

test-multi-line:
    DO tests+RUN_EARTHLY --earthfile=multi-line.earth --target=+test

test-multi-line-with-comment:
    DO tests+RUN_EARTHLY --earthfile=multi-line-with-comment.earth --target=+test

test-multi-line-with-comment2:
    DO tests+RUN_EARTHLY --earthfile=multi-line-with-comment2.earth --target=+test

test-multi-line-with-comment3:
    DO tests+RUN_EARTHLY --earthfile=multi-line-with-comment3.earth --target=+test

test-multi-line-with-comment4:
    DO tests+RUN_EARTHLY --earthfile=multi-line-with-comment4.earth --target=+test

test-multi-line-with-args:
    DO tests+RUN_EARTHLY --earthfile=multi-line-with-args.earth --target=+test

test-multi-line-with-args2:
    DO tests+RUN_EARTHLY --earthfile=multi-line-with-args2.earth --target=+test

test-multi-line-with-newline:
    DO tests+RUN_EARTHLY --earthfile=multi-line-with-empty-newline.earth --target=+test

test-version-only-import:
    RUN mkdir subdir
    RUN echo "VERSION 0.5" > subdir/Earthfile
    DO tests+RUN_EARTHLY --earthfile=version-only-import.earth --target=+test

test-version-only:
    DO tests+RUN_EARTHLY --earthfile=version-only.earth --target=+base
    RUN test "$(cat Earthfile | wc -l)" = "0"

test-comment-and-whitespace-before-version:
    DO tests+RUN_EARTHLY --earthfile=comment-and-whitespace-before-version.earth --target=+test

test-whitespace-then-version:
    DO tests+RUN_EARTHLY --earthfile=whitespace-then-version.earth --target=+test

test-all:
    BUILD +test-single-line
    BUILD +test-single-line-with-args
    BUILD +test-single-line-with-comment
    BUILD +test-multi-line
    BUILD +test-multi-line-with-comment
    BUILD +test-multi-line-with-comment2
    BUILD +test-multi-line-with-comment3
    BUILD +test-multi-line-with-comment4
    BUILD +test-multi-line-with-args
    BUILD +test-multi-line-with-args2
    BUILD +test-multi-line-with-newline
    BUILD +test-version-only
    BUILD +test-comment-and-whitespace-before-version
    BUILD +test-whitespace-then-version
    BUILD +test-version-only-import
