
build:
    FROM hashicorp/terraform:light

    ARG AWS_ACCESS_KEY_ID
    ARG AWS_SECRET_ACCESS_KEY
    ARG AWS_DEFAULT_REGION=us-east-1

    COPY aws/ .

    WITH DOCKER --pull localstack/localstack:0.11.5
        RUN docker run -d -p 4566:4566 -e SERVICES=s3 --name localstack --network="host" localstack/localstack:0.11.5 && \
            terraform init && \
            terraform plan && \
            terraform apply -auto-approve
    END

    SAVE ARTIFACT terraform.tfstate AS LOCAL aws/terraform.tfstate
    SAVE ARTIFACT terraform.tfstate.backup AS LOCAL aws/terraform.tfstate.backup