FROM golang:1.15-alpine3.13

RUN apk add --update --no-cache \
    openjdk11 \
    openssl \
    ca-certificates \
    curl

# Install antlr.
WORKDIR /usr/local/lib
RUN curl -O https://www.antlr.org/download/antlr-4.8-complete.jar
WORKDIR /earthly

parser:
    COPY ./*.g4 ./ast/parser/
    RUN java \
        -Xmx500M \
        -cp "/usr/local/lib/antlr-4.8-complete.jar:$CLASSPATH" \
        org.antlr.v4.Tool \
        -Dlanguage=Go \
        -lib ast/parser/EarthLexer.g4 \
        -lib ast/parser/EarthParser.g4 \
        ast/parser/EarthLexer.g4 \
        ast/parser/EarthParser.g4
    SAVE ARTIFACT ./ast/parser/*.go / AS LOCAL ./
