VERSION --try 0.6

test:
    FROM alpine:3.15
    ARG fail="false"
    RUN echo foo > otherdata
    TRY
        RUN echo "there's no data to save" && test "$fail" = "false"
    FINALLY
        SAVE ARTIFACT --if-exists data AS LOCAL .testdata
        SAVE ARTIFACT --if-exists otherdata AS LOCAL .otherdata
    END
