
steps:
  - label: Test
    commands:
      - ./.buildkite/tests.sh
    env:
      EARTHLY_INSTALL_ID: "earthly-buildkite-macos"
      EARTHLY_OS: "darwin-m1"
    agents:
      os: macOS
      arch: arm64
    timeout_in_minutes: 55
