
steps:
  - label: Test
    commands:
      - ./.buildkite/tests.sh
    env:
      EARTHLY_BUILD_ARGS: "DOCKERHUB_USER_SECRET=+secrets/earthly-technologies/dockerhub/user,DOCKERHUB_TOKEN_SECRET=+secrets/earthly-technologies/dockerhub/token"
    agents:
      os: macOS
