
steps:
  - label: Test
    commands:
      - bash ./.buildkite/tests.sh
    env:
      GIT_URL_INSTEAD_OF: "https://github.com/=git@github.com:"
      FORCE_COLOR: 1
      EARTH_OS: linux
      EARTHLY_CONFIG: "./.buildkite/earthly-config-win.yml"
    agents:
      os: wsl2
