
steps:
  - label: Test
    commands:
      - wsl -- bash --noprofile --norc -euo pipefail "$(script="$(wslpath '{0}')" && sed -i 's/\r$//' "$script" && echo "$script")" echo "Hello wsl"
    agents:
      os: windows
