
steps:
  - label: Test
    commands:
      - ./.buildkite/tests.sh
    env:
      EARTHLY_INSTALL_ID: "earthly-buildkite-windows"
      EARTHLY_BUILD_ARGS: "DOCKERHUB_USER_SECRET=+secrets/earthly-technologies/dockerhub/user,DOCKERHUB_TOKEN_SECRET=+secrets/earthly-technologies/dockerhub/token"
      FORCE_COLOR: 1
      EARTHLY_OS: linux
      EARTHLY_CONFIG: "./.buildkite/earthly-config-win.yml"
    agents:
      os: wsl2
    timeout_in_minutes: 55
