
all:
    BUILD \
        --build-arg BASE_IMAGE=docker:dind \
        --build-arg BASE_IMAGE=alpine:latest \
        --build-arg BASE_IMAGE=debian:stable \
        --build-arg BASE_IMAGE=debian:stable-slim \
        --build-arg BASE_IMAGE=ubuntu:latest \
        --build-arg BASE_IMAGE=amazonlinux:1 \
        --build-arg BASE_IMAGE=amazonlinux:2 \
        --build-arg BASE_IMAGE=../../..+dind-alpine \
        --build-arg BASE_IMAGE=../../..+dind-ubuntu \
        +test

test:
    ARG BASE_IMAGE
    FROM $BASE_IMAGE
    COPY ./docker-compose.yml ./
    WITH DOCKER --compose docker-compose.yml
        RUN true
    END
