all:
    BUILD \
        --build-arg BASE_IMAGE=docker:dind \
        --build-arg BASE_IMAGE=alpine:latest \
        --build-arg BASE_IMAGE=debian:stable \
        --build-arg BASE_IMAGE=debian:stable-slim \
        --build-arg BASE_IMAGE=ubuntu:latest \
        --build-arg BASE_IMAGE=amazonlinux:1 \
        --build-arg BASE_IMAGE=amazonlinux:2 \
        --build-arg BASE_IMAGE=../../..+dind-alpine \
        --build-arg BASE_IMAGE=../../..+dind-ubuntu \
        +test

test:
    ARG BASE_IMAGE
    FROM $BASE_IMAGE
    COPY ./docker-compose.yml ./
    RUN cat docker-compose.yml && md5sum docker-compose.yml | grep b6626aeca817ea311ae8f1555c01a9cb
    WITH DOCKER --compose docker-compose.yml
        RUN true
    END
