
ARG REGISTRY="127.0.0.1:5000"

test1:
    FROM alpine:3.11
    RUN echo "execute-test1-run-before-copy"
    COPY ./input ./
    RUN echo "execute-test1-run-after-copy"
    SAVE IMAGE --push $REGSITRY/test1:latest
