VERSION 0.7
PROJECT earthly-technologies/core

ARG DOCKERHUB_USER_SECRET=+secrets/DOCKERHUB_USER
ARG DOCKERHUB_TOKEN_SECRET=+secrets/DOCKERHUB_TOKEN
ARG DOCKERHUB_MIRROR
ARG DOCKERHUB_MIRROR_INSECURE=false
ARG DOCKERHUB_MIRROR_HTTP=false
ARG DOCKERHUB_AUTH=true
FROM ../..+earthly-integration-test-base \
    --DOCKERHUB_AUTH=$DOCKERHUB_AUTH \
    --DOCKERHUB_USER_SECRET=$DOCKERHUB_USER_SECRET \
    --DOCKERHUB_TOKEN_SECRET=$DOCKERHUB_TOKEN_SECRET \
    --DOCKERHUB_MIRROR=$DOCKERHUB_MIRROR \
    --DOCKERHUB_MIRROR_INSECURE=$DOCKERHUB_MIRROR_INSECURE \
    --DOCKERHUB_MIRROR_HTTP=$DOCKERHUB_MIRROR_HTTP

IMPORT .. AS tests

RUN apk add bash
WORKDIR /test

test-dockerhub:
    COPY lock.sh unlock.sh \
        test-dockerhub-project.sh test-dockerhub-user.sh \
        .
    RUN --secret EARTHLY_TOKEN=fake-user-write-token \
        --secret AWS_ACCESS_KEY_ID=aws/ci-cd-access-key \
        --secret AWS_SECRET_ACCESS_KEY=aws/ci-cd-access-secret \
        ./lock.sh && ( \
            ./test-dockerhub-user.sh && \
            ./test-dockerhub-project.sh && \
            true) || ( ./unlock.sh && echo "dockerhub test failed"; exit 1) && ./unlock.sh

test-ecr:
    COPY lock.sh unlock.sh \
        test-ecr.sh \
        test-ecr-project.sh test-ecr-user.sh \
        .

    ENV EARTHLY_EXEC_CMD=/test/test-ecr.sh
    RUN --secret EARTHLY_TOKEN=fake-user-write-token \
        --secret AWS_ACCESS_KEY_ID=aws/ci-cd-access-key \
        --secret AWS_SECRET_ACCESS_KEY=aws/ci-cd-access-secret \
        --mount=type=tmpfs,target=/tmp/earthly \
        --privileged \
        --entrypoint \
        --mount=type=tmpfs,target=/tmp/earthly

test-gcp:
    COPY lock.sh unlock.sh \
        test-gcp.sh \
        test-gcp-project.sh test-gcp-user.sh \
        .

    ENV EARTHLY_EXEC_CMD=/test/test-gcp.sh
    RUN --secret EARTHLY_TOKEN=fake-user-write-token \
        --secret GCP_KEY=gcp/ci-cd-key \
        --mount=type=tmpfs,target=/tmp/earthly \
        --privileged \
        --entrypoint \
        --mount=type=tmpfs,target=/tmp/earthly

test-multi:
    COPY lock.sh unlock.sh \
        test-multi.sh \
        .

    ENV EARTHLY_EXEC_CMD=/test/test-multi.sh
    RUN --secret EARTHLY_TOKEN=fake-user-write-token \
        --secret GCP_KEY=gcp/ci-cd-key \
        --secret AWS_ACCESS_KEY_ID=aws/ci-cd-access-key \
        --secret AWS_SECRET_ACCESS_KEY=aws/ci-cd-access-secret \
        --mount=type=tmpfs,target=/tmp/earthly \
        --privileged \
        --entrypoint \
        --mount=type=tmpfs,target=/tmp/earthly

test:
    BUILD +test-dockerhub
    BUILD +test-ecr
    BUILD +test-gcp
    BUILD +test-multi
