<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>$schema</key>
    <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
    <key>fileTypes</key>
      <array>
        <string>Earthfile</string>
      </array>
    <key>name</key>
    <string>Earthfile</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constant</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#entity</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keyword</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#string</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#variable</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#target</string>
      </dict>
    </array>
    <key>scopeName</key>
    <string>source.earthfile</string>
    <key>repository</key>
    <dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.whitespace.comment.leading.earthfile</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>comment.line.number-sign.earthfile</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.earthfile</string>
              </dict>
            </dict>
            <key>comment</key>
            <string>comment.line</string>
            <key>match</key>
            <string>^(\s*)((#).*$\n?)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.line.earthfile</string>
            <key>match</key>
            <string>(\s+)((#).*$\n?)</string>
          </dict>
        </array>
      </dict>
      <key>constant</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>constant.character.escape.earthfile</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\$</string>
            <key>name</key>
            <string>constant.character.escape.earthfile</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=EXPOSE\s)(\d+)</string>
            <key>name</key>
            <string>constant.numeric.earthfile</string>
          </dict>
        </array>
      </dict>
      <key>keyword</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.operator.shell.earthfile</string>
            <key>match</key>
            <string>((&amp;&amp;)|(&gt;&gt;)|(&lt;&lt;)|[|;&gt;])</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.earthfile</string>
            <key>match</key>
            <string>([=])</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.flag.earthfile</string>
            <key>match</key>
            <string>(\B(-)+[a-zA-Z0-9\-]+)</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#special-method</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#target</string>
          </dict>
        </array>
      </dict>
      <key>target</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.target.earthfile</string>
              </dict>
            </dict>
            <key>match</key>
            <string>^\s*(([a-zA-Z0-9.]|-)+):</string>
          </dict>
        </array>
      </dict>
      <key>special-method</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.special-method.earthfile</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.variable.target.earthfile</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.other.special-method.earthfile</string>
              </dict>
            </dict>
            <key>match</key>
            <string>^\s*\b(SAVE ARTIFACT)(\b.*?\b)(AS LOCAL)\b</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.special-method.earthfile</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.base-image.earthfile</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(?&lt;=(^FROM\s))(\S+)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other.special-method.earthfile</string>
            <key>match</key>
            <string>^\s*HEALTHCHECK\s+(NONE|CMD)\s</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other.special-method.earthfile</string>
            <key>match</key>
            <string>^\s*FROM DOCKERFILE\s</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other.special-method.earthfile</string>
            <key>match</key>
            <string>^\s*(FROM|COPY|SAVE ARTIFACT|SAVE IMAGE|RUN|LABEL|EXPOSE|VOLUME|USER|ENV|ARG|BUILD|WORKDIR|ENTRYPOINT|CMD|GIT CLONE|DOCKER LOAD|DOCKER PULL|HEALTHCHECK|WITH DOCKER|END)\s</string>
          </dict>
        </array>
      </dict>
      <key>string</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>"</string>
            <key>end</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.earthfile</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.earthfile</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.earthfile</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\\.</string>
                <key>name</key>
                <string>constant.character.escaped.earthfile</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>'</string>
            <key>end</key>
            <string>'</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.earthfile</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.earthfile</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.single.earthfile</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\\.</string>
                <key>name</key>
                <string>constant.character.escaped.earthfile</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>variable</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\$[a-zA-Z0-9_\-]+</string>
            <key>name</key>
            <string>variable.other.earthfile</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=\${)([a-zA-Z0-9.\-_]+)(?=})</string>
            <key>name</key>
            <string>variable.other.earthfile</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\$\{</string>
            <key>end</key>
            <string>\}</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.variable.begin.earthfile</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.variable.end.earthfile</string>
              </dict>
            </dict>
            <key>name</key>
            <string>variable.other.earthfile</string>
            <key>patterns</key>
            <array/>
          </dict>
        </array>
      </dict>
      <key>entity</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>([a-zA-Z0-9._\-/:]*\+[a-zA-Z0-9.\-]+(/\S*)+)</string>
            <key>name</key>
            <string>entity.name.variable.target.earthfile</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([a-zA-Z0-9._\-/:]*\+[a-zA-Z0-9.\-]+)</string>
            <key>name</key>
            <string>entity.name.type.target.earthfile</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>