
FROM alpine:3.13
WORKDIR /tutorial

part1:
    COPY --dir ./part1 ./
    SAVE ARTIFACT ./part1

part3:
    COPY --dir ./part3 ./
    SAVE ARTIFACT ./part3

part4:
    COPY --dir ./part4 ./
    SAVE ARTIFACT ./part4

part5:
    COPY --dir ./part5 ./
    SAVE ARTIFACT ./part5
