name: Bug report
description: Report an unexpected problem
labels: ["type:bug"]
assignees: []
body:
  - type: textarea
    id: what-went-wrong
    attributes:
      label: What went wrong?
      description: Can you describe what happened? Can you reproduce it? If so, please list the steps to reproduce the issue. Do you have an Earthfile that you can share which showcases the problem? If so, please include it here.
    validations:
      required: true
  - type: textarea
    id: what-should-have-happened
    attributes:
      label: What should have happened?
      description: Can you describe the expected outcome? Have you found any workarounds? Can you share them for any other users who might be experiencing the issue?
    validations:
      required: true
  - type: textarea
    id: earthly-version
    attributes:
      label: What earthly version?
      description: Please include the output of `earthly --version`
    validations:
      required: true
  - type: textarea
    id: buildkit-logs
    attributes:
      label: Buildkit Logs
      description: If buildkit crashed, please include the output of `docker logs earthly-buildkitd`
    validations:
      required: false
  - type: textarea
    id: other-helpful-information
    attributes:
      label: Other Helpful Information
      description: |
        Please include any additional information you might have. e.g. the output when `--verbose` is enabled, any stack traces, or even screenshots (if text is rendered incorrectly).
    validations:
      required: false
