name: Feature proposal
description: Submit an idea for a new feature
title: 'proposal: '
labels: ["type:proposal"]
assignees: []
body:
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Please describe the reason that you need or want this change.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Please describe how you expect the change to work. Ideally, follow the style of reproduction steps - the steps that you expect to take, followed by the expected outcome.
    validations:
      required: true
