VERSION 0.6
FROM --platform=linux/amd64 node:latest
WORKDIR /app

deps:
    ARG auth_token
    ARG site_id
    # Set environment variables required for building and deploying to Netlify
    ENV NETLIFY_AUTH_TOKEN=$auth_token
    ENV NETLIFY_SITE_ID=$site_id
    # Install the Netlify CLI
    RUN npm install netlify-cli -g
    # Copy files required for building and deploying to Netlify
    COPY netlify.toml ./

build:
    FROM +deps
    # Copy files required for building
    COPY next-env.d.ts package.json styles.module.css tsconfig.json ./
    # Copy directories required for building
    COPY --dir pages ./
    # Install required packages
    RUN npm install netlify-cli --save-dev
    RUN npm install @netlify/plugin-nextjs --save-dev
    RUN npm install
    # Build site
    RUN netlify build --context production
    SAVE ARTIFACT ./node_modules node_modules/ AS LOCAL ./
    SAVE ARTIFACT ./.next .next/ AS LOCAL ./
    SAVE ARTIFACT ./.netlify .netlify/ AS LOCAL ./

deploy:
    FROM +deps
    # Copy artifacts required for deploying to Netlify
    COPY +build/node_modules/ +build/.next/ +build/.netlify/ ./
    # Deploy site
    RUN netlify deploy --prod
