VERSION 0.6

ARG DOCKERHUB_USER_SECRET=+secrets/DOCKERHUB_USER
ARG DOCKERHUB_TOKEN_SECRET=+secrets/DOCKERHUB_TOKEN
ARG DOCKERHUB_MIRROR
ARG DOCKERHUB_AUTH=true
FROM ../..+earthly-integration-test-base \
    --DOCKERHUB_AUTH=$DOCKERHUB_AUTH \
    --DOCKERHUB_USER_SECRET=$DOCKERHUB_USER_SECRET \
    --DOCKERHUB_TOKEN_SECRET=$DOCKERHUB_TOKEN_SECRET \
    --DOCKERHUB_MIRROR=$DOCKERHUB_MIRROR

IMPORT .. AS tests

WORKDIR /test

all:
    BUILD +copy
    BUILD +copy-verbose-output
    BUILD +copy-with-parents
    BUILD +copy-with-parents-and-local-path
    BUILD +copy-invalid

copy:
    RUN mkdir -p in/sub/1 in/sub/2 && \
        echo "root" > in/root && \
        echo "1" > in/sub/1/file && \
        echo "2" > in/sub/2/file && \
        echo "sub" > in/sub/file
    DO +RUN_EARTHLY_ARGS --earthfile=copy.earth

copy-verbose-output:
    RUN mkdir -p subdir/a.txt && \
        echo -n "a" > a.txt && \
        echo -n "alpha" > alpha.txt && \
        echo -n "beta" > subdir/a.txt/beta.txt
    RUN mkdir -p /opt/test && \
        echo "foo" > /opt/test/foo && \
        echo "bar" > /opt/test/bar
    # Setup a test that runs earthly twice; both instances of earthly must be run
    # back to back as the file caching logic references the directories inode ID while constructing
    # the shared cache key.
    RUN echo "#!/bin/sh
set -x
earthly --config \$earthly_config --verbose +all 2>output.txt;
earthly --config \$earthly_config --verbose +all 2>output2.txt;
" >/tmp/multiple-earthly-script && chmod +x /tmp/multiple-earthly-script

    DO +RUN_EARTHLY_ARGS --earthfile=copy-verbose.earth --exec_cmd=/tmp/multiple-earthly-script

    # test that the first run sends a.txt and doesn't send any non-referenced files
    RUN cat output.txt
    RUN cat output.txt | grep 'sent data for a.txt (1 B)'
    RUN cat output.txt | grep 'sent data for ../opt/test/foo (4 B)'
    RUN if grep "sent data for alpha.txt" output.txt >/dev/null; then echo "alpha.txt should not have been sent"; exit 1; fi
    RUN if grep "sent data for .*beta.txt" output.txt >/dev/null; then echo "beta.txt should not have been sent"; exit 1; fi
    RUN if grep "sent data for ../opt/test/bar" output.txt >/dev/null; then echo "../opt/test/bar should not have been sent"; exit 1; fi

    # test that the second run did not resend a.txt (or any other non-referenced files)
    RUN cat output2.txt
    RUN if grep "sent data for a.txt" output2.txt >/dev/null; then echo "a.txt should not have been sent"; exit 1; fi
    RUN if grep "sent data for ../opt/test/foo" output2.txt >/dev/null; then echo "../opt/test/foo should not have been sent"; exit 1; fi
    RUN if grep "sent data for alpha.txt" output2.txt >/dev/null; then echo "alpha.txt should not have been sent"; exit 1; fi
    RUN if grep "sent data for .*beta.txt" output2.txt >/dev/null; then echo "beta.txt should not have been sent"; exit 1; fi
    RUN if grep "sent data for ../opt/test/bar" output2.txt >/dev/null; then echo "../opt/test/bar should not have been sent"; exit 1; fi

copy-with-parents:
    WORKDIR /test/workdir
    ENV SRC_DIR=/test/workdir
    RUN mkdir -p /test/test1 && \
        echo "bar1" > /test/test1/foo1
    RUN mkdir -p /opt/test2 && \
        echo "bar2" > /opt/test2/foo2
    RUN mkdir -p /test/workdir/test3 && \
        echo "bar3" > /test/workdir/test3/foo3
    DO +RUN_EARTHLY_ARGS --earthfile=with-parents.earth

copy-with-parents-and-local-path:
    WORKDIR /test/workdir
    ENV SRC_DIR=/test
    RUN mkdir -p /test/test1 && \
        echo "bar1" > /test/test1/foo1
    DO +RUN_EARTHLY_ARGS --earthfile_dest=/test/workdir/Earthfile --earthfile=with-parents-and-local-path.earth --target=./workdir+all

copy-invalid:
    RUN mkdir -p /test/test1 && \
        echo "bar2" > /test/test1/foo1
    RUN mkdir -p /opt/test2 && \
        echo "bar1" > /opt/test2/foo2
    DO +RUN_EARTHLY_ARGS --should_fail=true --earthfile=invalid.earth --target=+multi-parent-context
    DO +RUN_EARTHLY_ARGS --should_fail=true --earthfile=invalid.earth --target=+all-parent-dir
    DO +RUN_EARTHLY_ARGS --should_fail=true --earthfile=with-parent-no-feature-flag.earth --target=+all

RUN_EARTHLY_ARGS:
    COMMAND
    ARG earthfile
    ARG earthfile_dest="./Earthfile"
    ARG target=+all
    ARG should_fail=false
    ARG exec_cmd=$exec_cmd
    DO tests+RUN_EARTHLY \
        --earthfile=$earthfile \
	--earthfile_dest=$earthfile_dest \
        --target=$target \
	--exec_cmd=$exec_cmd \
        --should_fail=$should_fail \
        --DOCKERHUB_AUTH=$DOCKERHUB_AUTH \
        --DOCKERHUB_USER_SECRET=$DOCKERHUB_USER_SECRET \
        --DOCKERHUB_TOKEN_SECRET=$DOCKERHUB_TOKEN_SECRET \
        --DOCKERHUB_MIRROR=$DOCKERHUB_MIRROR
