
vim: Earthfile.vim
	mkdir -p ~/.vim/{syntax,ftdetect}
	cp Earthfile.vim ~/.vim/syntax/Earthfile.vim
	echo "au BufRead,BufNewFile Earthfile set filetype=Earthfile" > ~/.vim/ftdetect/Earthfile.vim
	echo "au BufRead,BufNewFile build.earth set filetype=Earthfile" >> ~/.vim/ftdetect/Earthfile.vim
