VERSION 0.7 
FROM clojure:temurin-8-lein
WORKDIR /var/app

build:
    COPY earthly-example/ .
    RUN lein uberjar
    SAVE ARTIFACT target/uberjar/earthly-example-*-standalone.jar earthly-example-standalone.jar

docker:
    FROM openjdk:22-slim-bullseye
    RUN apt update && apt install zip -y 
    COPY +build/earthly-example-standalone.jar earthly-example-standalone.jar
    EXPOSE 8080
    ENTRYPOINT java -Dserver.port=8080 -jar earthly-example-standalone.jar
    COPY extractJarVersion extractJarVersion
    ARG tag = "$(./extractJarVersion earthly-example-standalone.jar)"
    SAVE IMAGE clojure-example:${tag}
