VERSION 0.7 
FROM clojure:temurin-8-lein
WORKDIR /var/app

ARG --global CLOJURE_STANDALONE_ARTIFACT="target/uberjar/earthly-example-0.1.0-SNAPSHOT-standalone.jar"

build:
    COPY earthly-example/ .
    RUN lein uberjar
    SAVE ARTIFACT ${CLOJURE_STANDALONE_ARTIFACT} ${CLOJURE_STANDALONE_ARTIFACT}

docker:
    FROM openjdk:22-jdk
    COPY +build/${CLOJURE_STANDALONE_ARTIFACT} ${CLOJURE_STANDALONE_ARTIFACT}
    EXPOSE 8080
    ENTRYPOINT java -Dserver.port=8080 -jar ${CLOJURE_STANDALONE_ARTIFACT}
    SAVE IMAGE clojure-example:latest
