VERSION 0.6
FROM earthly/dind:alpine

all:
    BUILD +docker-load-test
    # Temporarily disabled.
    # BUILD +undeclared-pull-test
    BUILD +docker-pull-test
    BUILD +load-parallel-test
    BUILD +one-target-many-names
    BUILD +if-after

a-test-image:
    FROM alpine:3.13
    RUN mkdir /abc
    WORKDIR /abc
    RUN echo "hello world" >def.txt
    ENTRYPOINT cat /abc/def.txt && pwd
    SAVE IMAGE test-img:xyz

docker-load-test:
    # Index is used to create parallel tests.
    ARG INDEX=0
    RUN echo "$INDEX"
    WITH DOCKER \
            --pull hello-world \
            --load +a-test-image
        RUN docker run test-img:xyz && \
            docker run hello-world
    END

# This test is testing whether a pull within a WITH DOCKER would work.
# Currently it fails occasionally due to DockerHub rate limiting.
# undeclared-pull-test:
#     WITH DOCKER
#         RUN docker run hello-world
#     END

docker-pull-test:
    # Note that this is mainly a smoke test, because the RUN command
    # works even in absence of the --pull (it pull automatically if image
    # not present).
    WITH DOCKER --pull hello-world
        RUN docker run hello-world
    END

load-parallel-test:
    BUILD \
        +docker-load-test \
        --INDEX=1 \
        --INDEX=2 \
        --INDEX=3 \
        --INDEX=4 \
        --INDEX=5

multi-from-one:
    FROM hello-world

multi-from-two:
    FROM alpine:latest

one-target-many-names:
    FROM earthly/dind:alpine
    WITH DOCKER \
            --load a:latest=+multi-from-one \  # Test that there can be multiple names assigned to an image from a single target
            --load b:latest=+multi-from-one \
            --load c:latest=+multi-from-two    # Test that nothing else broke, load from another target
        RUN docker images && \
            docker run a:latest && \
            echo "-----" && \
            docker run b:latest && \
            echo "-----" && \
            docker run c:latest uname -a
    END

if-after:
    FROM earthly/dind:alpine
    WITH DOCKER --load a:latest=+multi-from-one
        RUN docker run a:latest
    END

    IF [ "true" = "true" ]
        RUN true
    END
