VERSION --use-registry-for-with-docker 0.6

all:
    BUILD +test

fetch:
    FROM alpine:3.10
    RUN apk add curl
    COPY fetch.sh /bin/fetch
    CMD ["/bin/fetch"]

test:
    LOCALLY
    ARG FRONTEND=docker
    WITH DOCKER \
            --compose docker-compose.yml \
            --service webserver \
            --load fetch:latest=+fetch
        RUN $FRONTEND compose up --exit-code-from fetch fetch | grep 'Hello World'
    END
