VERSION --for-in 0.5

FROM alpine:3.13

IMPORT ../ AS common

build:
    RUN echo building lib1
    DO ../+INSTALL_WHLS --wheels="lib2"

build-imported:
    RUN echo building lib1 using IMPORT
    DO common+INSTALL_WHLS --wheels="lib2"
