FROM ../../..+earth-docker

test-root-commands:
    RUN echo "./
bootstrap 
org 
secrets 
register 
debug 
prune " > expected
    RUN COMP_LINE="earth " COMP_POINT=6 earth > actual
    RUN diff expected actual

test-targets:
    COPY fake.earth ./Earthfile
    RUN echo "+mytarget 
+othertarget " > expected
    RUN COMP_LINE="earth +" COMP_POINT=7 earth > actual
    RUN diff expected actual
    RUN echo "+mytarget " > expected
    RUN COMP_LINE="earth +m" COMP_POINT=8 earth > actual
    RUN diff expected actual

test-relative-dir-targets:
    RUN mkdir -p /test/foo
    COPY fake.earth /test/foo/Earthfile
    WORKDIR /test/
    RUN echo "./foo+" > expected
    RUN COMP_LINE="earth ./" COMP_POINT=8 earth > actual
    RUN diff expected actual
    RUN echo "./foo+mytarget 
./foo+othertarget " > expected
    RUN COMP_LINE="earth ./foo+" COMP_POINT=12 earth > actual
    RUN diff expected actual

test-all:
    BUILD +test-root-commands
    BUILD +test-targets
    BUILD +test-relative-dir-targets
