FROM ../../..+earth-docker

test1:
    RUN echo "./
bootstrap 
org 
secrets 
register 
debug 
prune " > expected
    RUN COMP_LINE="earth " COMP_POINT=6 earth > actual
    RUN diff expected actual

test2:
    COPY fake.earth ./Earthfile
    RUN echo "+mytarget 
+othertarget " > expected
    RUN COMP_LINE="earth +" COMP_POINT=7 earth > actual
    RUN diff expected actual
    RUN echo "+mytarget " > expected
    RUN COMP_LINE="earth +m" COMP_POINT=8 earth > actual
    RUN diff expected actual

test:
    BUILD +test1
    BUILD +test2
