VERSION 0.6

ARG DOCKERHUB_USER_SECRET=+secrets/DOCKERHUB_USER
ARG DOCKERHUB_TOKEN_SECRET=+secrets/DOCKERHUB_TOKEN
ARG DOCKERHUB_MIRROR
ARG DOCKERHUB_AUTH=true
FROM ../..+earthly-integration-test-base \
    --DOCKERHUB_AUTH=$DOCKERHUB_AUTH \
    --DOCKERHUB_USER_SECRET=$DOCKERHUB_USER_SECRET \
    --DOCKERHUB_TOKEN_SECRET=$DOCKERHUB_TOKEN_SECRET \
    --DOCKERHUB_MIRROR=$DOCKERHUB_MIRROR

test:
    COPY expected-*.yml .
    
    # Ensure earthly doesn't create overridden config files when they don't exist
    RUN earthly --config config.yml config global.disable_analytics true 2>&1 | grep 'failed to read from config.yml: open config.yml: no such file or directory'
    
    RUN touch config.yml

    # Adding various configs of different types
    RUN earthly --config config.yml config global.disable_analytics true
    RUN test "$(cat config.yml)" = "$(cat expected-1.yml)"
    
    RUN earthly --config config.yml config 'git."example.com".password' hunter2
    RUN test "$(cat config.yml)" = "$(cat expected-2.yml)"
    
    RUN earthly --config config.yml config global.buildkit_additional_args "['userns', '--host']"
    RUN test "$(cat config.yml)" = "$(cat expected-3.yml)"
    
    RUN earthly --config config.yml config global.conversion_parallelism 5
    RUN test "$(cat config.yml)" = "$(cat expected-4.yml)"

    # --delete should remove a config
    RUN earthly --config config.yml config global.conversion_parallelism --delete
    RUN test "$(cat config.yml)" = "$(cat expected-5.yml)"

    # --help and -h should succeed
    RUN earthly config global.conversion_parallelism --help
    RUN earthly config global.conversion_parallelism -h
    # Ensure configs haven't changed by running help
    RUN test "$(cat config.yml)" = "$(cat expected-5.yml)"

    # Edge cases
    RUN earthly --config config.yml config global.conversion_parallelism oops; test $? = 1
    RUN earthly --config config.yml config global.conversion_parallelism ""; test $? = 1
    RUN earthly --config config.yml config global.buildkit_image ""
