VERSION 0.8
FROM node:13.10.1-alpine3.11

WORKDIR /example-multirepo

docker:
    RUN npm install -g http-server
    COPY ../html+html/* ./
    COPY ../js+build/* ./
    EXPOSE 8080
    ENTRYPOINT ["http-server", "."]
    SAVE IMAGE --push earthly/examples:monorepo
