VERSION 0.5
FROM alpine:3.13

myimage-fromtest:
    FROM github.com/earthly/test-remote/save-image:main+saveimage
    RUN echo "358718f8-ff97-45b0-8670-3edd69b335ba" > myimage
    SAVE IMAGE myimage:old-remote-from-test

myimage-copytest:
    COPY github.com/earthly/test-remote/save-image-with-artifact:main+saveimageandartifact/saveimageandartifact-data .
    RUN test "$(cat saveimageandartifact-data)" = "a119f6a9-9749-4035-8647-48d48bb6a361"
    RUN echo "3debd2b7-bc2c-4167-9e05-c6d628e8a13a" > myimage
    SAVE IMAGE myimage:old-remote-copy-test

myimage-buildtest:
    BUILD github.com/earthly/test-remote/save-image:main+saveimage
    RUN echo "dfb4215f-989e-41d1-84b8-3080e84783d3" > myimage
    SAVE IMAGE myimage:old-remote-build-test
