package command

const (
	Add            = "ADD"
	Arg            = "ARG"
	Build          = "BUILD"
	Cache          = "CACHE"
	Cmd            = "CMD"
	Command        = "COMMAND"
	Function       = "FUNCTION"
	Copy           = "COPY"
	Do             = "DO"
	Docker         = "DOCKER"
	Entrypoint     = "ENTRYPOINT"
	Env            = "ENV"
	Expose         = "EXPOSE"
	From           = "FROM"
	FromDockerfile = "FROM DOCKERFILE"
	GitClone       = "GIT CLONE"
	HealthCheck    = "HEALTHCHECK"
	Host           = "HOST"
	Import         = "IMPORT"
	Label          = "LABEL"
	Let            = "LET"
	Load           = "LOAD"
	Locally        = "LOCALLY"
	OnBuild        = "ONBUILD"
	Project        = "PROJECT"
	Run            = "RUN"
	SaveArtifact   = "SAVE ARTIFACT"
	SaveImage      = "SAVE IMAGE"
	Set            = "SET"
	Shell          = "SHELL"
	StopSignal     = "STOPSIGNAL"
	User           = "USER"
	Volume         = "VOLUME"
	Workdir        = "WORKDIR"
)
