VERSION 0.8

deps:
    FROM node:22-alpine3.18
    COPY package.json ./
    RUN npm install
    SAVE ARTIFACT data

uuid:
	FROM +deps
	COPY uuid.js .
	RUN node uuid.js > generated-uuid
	SAVE ARTIFACT generated-uuid
