VERSION 0.7

PROJECT earthly-technologies/core

load-target:
    FROM alpine
    RUN echo "hi" > /tmp/x
    SAVE IMAGE saved:latest

with-docker-load:
    FROM earthly/dind:alpine
    WITH DOCKER --load saved:latest=+load-target
         RUN echo "loaded"
    END

with-docker-load-no-alias:
    BUILD +load-target
    FROM earthly/dind:alpine
    WITH DOCKER --load +load-target
         RUN echo "loaded"
    END
