#!/usr/bin/env bash
set -e

if [ "$1" = "remove" ]; then
    UNABLE_TO_REMOVE="unable to remove earthly-related docker resources"

    rm -f /usr/share/bash-completion/completions/earthly
    rm -f /usr/local/share/zsh/site-functions/_earthly

    if ! command -v docker &> /dev/null
    then
        echo "docker was not found; $UNABLE_TO_REMOVE"
        exit
    fi

    if ! docker info 2>/dev/null >/dev/null
    then
        echo "unable to query docker daemon; $UNABLE_TO_REMOVE"
        exit
    fi

    echo "removing earthly-buildkitd docker container"
    docker rm --force earthly-buildkitd

    echo "removing earthly-cache docker volume"
    docker volume rm --force earthly-cache
fi
