FROM alpine:3.13

mysubimage:
    WORKDIR /data
    RUN echo mysubimage > mysubimage
    SAVE IMAGE mysubimage:test

myimage:
    FROM +mysubimage
    RUN echo myimage > myimage
    SAVE IMAGE myimage:test
