FROM alpine:3.13
RUN apk add jq
WORKDIR /test

ARG DOCKERHUB_USER_SECRET=+secrets/DOCKERHUB_USER
ARG DOCKERHUB_TOKEN_SECRET=+secrets/DOCKERHUB_TOKEN
ARG DOCKERHUB_MIRROR
ARG DOCKERHUB_AUTH=true

COPY ../..+earthly/earthly /usr/local/bin/earthly

all:
    BUILD \
        --build-arg TEST=build-arg \
        --build-arg TEST=builtin-args \
        --build-arg TEST=cache1 \
        --build-arg TEST=cache2 \
        --build-arg TEST=chown \
        --build-arg TEST=comments \
        --build-arg TEST=config \
        --build-arg TEST=copy \
        --build-arg TEST=dotenv \
        --build-arg TEST=empty-git \
        --build-arg TEST=end-comment \
        --build-arg TEST=env \
        --build-arg TEST=escape-dir1 \
        --build-arg TEST=escape-dir2 \
        --build-arg TEST=escape \
        --build-arg TEST=excludes \
        --build-arg TEST=fail \
        --build-arg TEST=fail-invalid-artifact \
        --build-arg TEST=file-copying \
        --build-arg TEST=from-expose \
        --build-arg TEST=gen-dockerfile \
        --build-arg TEST=git-clone \
        --build-arg TEST=host-bind \
        --build-arg TEST=if-exists \
        --build-arg TEST=lc \
        --build-arg TEST=no-cache-local-artifact \
        --build-arg TEST=non-transitive-args1 \
        --build-arg TEST=non-transitive-args2 \
        --build-arg TEST=privileged \
        --build-arg TEST=push-build \
        --build-arg TEST=push \
        --build-arg TEST=run-no-cache \
        --build-arg TEST=save-artifact-after-push \
        --build-arg TEST=scratch-test \
        --build-arg TEST=secrets \
        --build-arg TEST=star \
        --build-arg TEST=target-first-line \
        --build-arg TEST=transitive-args \
        --build-arg TEST=with-docker \
        --build-arg TEST=with-docker-compose \
        --build-arg TEST=command \
        --build-arg TEST=import \
        +test
    BUILD --build-arg INPUT_FROM_DIR=./ --build-arg INPUT_FROM_TARGET="" --build-arg TEST=if +test
    BUILD --build-arg INPUT_FROM_DIR=./ --build-arg INPUT_FROM_TARGET="" --build-arg TEST=for +test
    BUILD --build-arg INPUT_FROM_DIR=./ --build-arg INPUT_FROM_TARGET="" --build-arg TEST=empty-targets +test

update-all:
    BUILD \
        --build-arg TEST=build-arg \
        --build-arg TEST=builtin-args \
        --build-arg TEST=cache1 \
        --build-arg TEST=cache2 \
        --build-arg TEST=chown \
        --build-arg TEST=comments \
        --build-arg TEST=config \
        --build-arg TEST=copy \
        --build-arg TEST=dotenv \
        --build-arg TEST=empty-git \
        --build-arg TEST=end-comment \
        --build-arg TEST=env \
        --build-arg TEST=escape-dir1 \
        --build-arg TEST=escape-dir2 \
        --build-arg TEST=escape \
        --build-arg TEST=excludes \
        --build-arg TEST=fail \
        --build-arg TEST=fail-invalid-artifact \
        --build-arg TEST=file-copying \
        --build-arg TEST=from-expose \
        --build-arg TEST=gen-dockerfile \
        --build-arg TEST=git-clone \
        --build-arg TEST=host-bind \
        --build-arg TEST=if-exists \
        --build-arg TEST=lc \
        --build-arg TEST=no-cache-local-artifact \
        --build-arg TEST=non-transitive-args1 \
        --build-arg TEST=non-transitive-args2 \
        --build-arg TEST=privileged \
        --build-arg TEST=push-build \
        --build-arg TEST=push \
        --build-arg TEST=run-no-cache \
        --build-arg TEST=save-artifact-after-push \
        --build-arg TEST=scratch-test \
        --build-arg TEST=secrets \
        --build-arg TEST=star \
        --build-arg TEST=target-first-line \
        --build-arg TEST=transitive-args \
        --build-arg TEST=with-docker \
        --build-arg TEST=with-docker-compose \
        --build-arg TEST=command \
        --build-arg TEST=import \
        +update-expected
    BUILD --build-arg INPUT_FROM_DIR=./ --build-arg INPUT_FROM_TARGET="" --build-arg TEST=if +update-expected
    BUILD --build-arg INPUT_FROM_DIR=./ --build-arg INPUT_FROM_TARGET="" --build-arg TEST=for +update-expected
    BUILD --build-arg INPUT_FROM_DIR=./ --build-arg INPUT_FROM_TARGET="" --build-arg TEST=empty-targets +update-expected

# Note: If this test fails for expected reasons (eg format of AST has changed), you can
#       update the expectations via +update-all. Please review the resulting diff
#       carefully when committing to git.
test:
    ARG TEST
    ARG INPUT_FROM_DIR=../../tests
    ARG INPUT_FROM_TARGET=ast-test-input
    DO +INPUT_COPY --TEST=$TEST --INPUT_FROM_DIR=$INPUT_FROM_DIR --INPUT_FROM_TARGET=$INPUT_FROM_TARGET
    COPY ${TEST}.ast.json ./expected.json
    RUN jq -S . ./expected.json >./expected.pretty.json
    RUN earthly debug ast ${TEST}.earth >./actual.json
    RUN jq -S . ./actual.json >./actual.pretty.json
    RUN diff ./actual.pretty.json ./expected.pretty.json

update-expected:
    ARG TEST
    ARG INPUT_FROM_DIR=../../tests
    ARG INPUT_FROM_TARGET=ast-test-input
    DO +INPUT_COPY --TEST=$TEST --INPUT_FROM_DIR=$INPUT_FROM_DIR --INPUT_FROM_TARGET=$INPUT_FROM_TARGET
    RUN earthly debug ast ${TEST}.earth >./expected.json
    RUN jq -S . ./expected.json >./expected.pretty.json
    SAVE ARTIFACT ./expected.pretty.json AS LOCAL ./${TEST}.ast.json

INPUT_COPY:
    COMMAND
    ARG TEST
    ARG INPUT_FROM_DIR
    ARG INPUT_FROM_TARGET

    IF [[ -z $INPUT_FROM_TARGET ]]
        COPY ${INPUT_FROM_DIR}${TEST}.earth ./
    ELSE
        COPY \
            --build-arg DOCKERHUB_AUTH=$DOCKERHUB_AUTH \
            --build-arg DOCKERHUB_USER_SECRET=$DOCKERHUB_USER_SECRET \
            --build-arg DOCKERHUB_TOKEN_SECRET=$DOCKERHUB_TOKEN_SECRET \
            --build-arg DOCKERHUB_MIRROR=$DOCKERHUB_MIRROR \
            ${INPUT_FROM_DIR}+${INPUT_FROM_TARGET}/${TEST}.earth .
    END
