VERSION 0.5
FROM alpine:3.13

mysubimage:
    WORKDIR /data
    RUN echo f0b94bbc-0451-4edb-b141-8829bfda076d > mysubimage
    SAVE IMAGE mysubimage:buildtest

myimage:
    FROM +mysubimage
    RUN echo 4a62afce-daf7-489b-918e-fdf08f95c8f6 > myimage
    SAVE IMAGE myimage:buildtest
