setup:
    COPY test .

test-glob:
    FROM +setup
    SAVE ARTIFACT ./* AS LOCAL out-glob/

test-dot:
    FROM +setup
    SAVE ARTIFACT . AS LOCAL out-dot/

test-dot-slash:
    FROM +setup
    SAVE ARTIFACT ./ AS LOCAL out-dot-slash/

test-sub:
    FROM +setup
    SAVE ARTIFACT ./sub AS LOCAL out-sub/

test-sub-glob:
    FROM +setup
    SAVE ARTIFACT ./sub/* AS LOCAL out-sub-glob/

test-dot-single:
    FROM +setup
    SAVE ARTIFACT ./sub/file AS LOCAL out-dot-single/

test-rel-single:
    FROM +setup
    SAVE ARTIFACT sub/file AS LOCAL out-rel-single/

test-src-dest:
    FROM +setup
    SAVE ARTIFACT sub/file my-dir/file AS LOCAL out-src-dest/

test-src-dest-rename:
    FROM +setup
    SAVE ARTIFACT sub/2 my-dir/my-file AS LOCAL out-src-dest-rename/

test-src-dest-destpath:
    FROM +setup
    SAVE ARTIFACT sub/2 ./my-dir/also-my-dir/file AS LOCAL out-src-dest-destpath/

test-src-dest-destdir:
    FROM +setup
    SAVE ARTIFACT sub/2 ./my-dir/ AS LOCAL out-src-dest-destdir/

test-src-dest-srcdir:
    FROM +setup
    SAVE ARTIFACT sub ./my-dir AS LOCAL out-src-dest-srcdir/

test:
    BUILD +test-glob
    BUILD +test-dot
    BUILD +test-dot-slash
    BUILD +test-sub
    BUILD +test-sub-glob
    BUILD +test-dot-single
    BUILD +test-rel-single
    BUILD +test-src-dest
    BUILD +test-src-dest-rename
    BUILD +test-src-dest-destpath
    BUILD +test-src-dest-destdir
    BUILD +test-src-dest-srcdir
