VERSION 0.8

all:
    ARG FRONTEND=docker
    ARG FRONTEND_COMPOSE="docker compose"
    BUILD +test

fetch:
    FROM alpine:3.18
    RUN apk add curl
    COPY fetch.sh /bin/fetch
    CMD ["/bin/fetch"]

test:
    LOCALLY
    ARG FRONTEND=docker
    ARG FRONTEND_COMPOSE="docker compose"
    ARG acbgrep=../../../scripts/acbtest/acbgrep
    RUN test -f "$acbgrep"
    WITH DOCKER \
            --compose docker-compose.yml \
            --service webserver \
            --load fetch:latest=+fetch
        RUN $FRONTEND_COMPOSE up --exit-code-from fetch fetch | "$acbgrep" 'Hello World'
    END
