VERSION 0.8

all:
    BUILD +test \
        --BASE_IMAGE=docker:20.10.14-dind \
        --BASE_IMAGE=docker:20.10.15-dind \
        --BASE_IMAGE=docker:dind \
        --BASE_IMAGE=alpine:latest \
        --BASE_IMAGE=debian:stable \
        --BASE_IMAGE=debian:stable-slim \
        --BASE_IMAGE=ubuntu:latest \
        --BASE_IMAGE=amazonlinux:1 \
        --BASE_IMAGE=amazonlinux:2 \
        --BASE_IMAGE=earthly/dind:alpine-3.19-docker-25.0.2-r0 \
        --BASE_IMAGE=earthly/dind:ubuntu-20.04-docker-24.0.5-1 \
        --BASE_IMAGE=earthly/dind:ubuntu-23.04-docker-24.0.5-1

test:
    ARG --required BASE_IMAGE
    FROM $BASE_IMAGE
    WORKDIR /root
    COPY ./docker-compose.yml ./
    WITH DOCKER --compose docker-compose.yml
        RUN true
    END
