VERSION 0.6

all:
    BUILD +test \
        --BASE_IMAGE=docker:dind \
        --BASE_IMAGE=alpine:latest \
        --BASE_IMAGE=debian:stable \
        --BASE_IMAGE=debian:stable-slim \
        --BASE_IMAGE=ubuntu:latest \
        --BASE_IMAGE=amazonlinux:1 \
        --BASE_IMAGE=amazonlinux:2 \
        --BASE_IMAGE=../..+dind-alpine \
        --BASE_IMAGE=../..+dind-ubuntu

test:
    ARG BASE_IMAGE
    FROM $BASE_IMAGE
    COPY ./docker-compose.yml ./
    WITH DOCKER --compose docker-compose.yml
        RUN true
    END
