VERSION 0.6
FROM golang:1.15-alpine3.13
WORKDIR /go-example

build:
    FROM ./services/service-one+deps
    COPY main.go .
    RUN go build -o build/go-example main.go
    SAVE ARTIFACT build/go-example /go-example AS LOCAL build/go-example

docker:
    ARG tag='latest'
    COPY +build/go-example .
    ENTRYPOINT ["/go-example/go-example"]
    SAVE IMAGE go-example:$tag
