FROM hseeberger/scala-sbt:8u265_1.4.0_2.12.12
WORKDIR /scala-example

project-files:
    COPY build.sbt ./
    COPY project project
    # Run sbt for caching purposes.
    RUN touch a.scala && sbt compile && rm a.scala
    SAVE IMAGE

build:
    FROM +project-files
    COPY src src
    RUN sbt compile
    SAVE IMAGE

unit-test:
    FROM +project-files
    COPY src src
    RUN sbt test

integration-test:
    FROM +project-files
    COPY src src
    COPY docker-compose.yml ./ 
    WITH DOCKER --compose docker-compose.yml
       RUN sbt it:test
    END

docker:
    FROM +project-files
    COPY src src
    RUN sbt 'set test in assembly := {}' assembly
    ENTRYPOINT ["java","-cp","target/scala-2.12/scala-example-assembly-1.0.jar","Main"]
    SAVE IMAGE scala-example:latest

smoke-test:
    FROM +project-files
    COPY docker-compose.yml ./ 
    COPY src/smoketest ./ 
    WITH DOCKER --compose docker-compose.yml --load scala-example:latest=+docker
        RUN ./smoketest.sh
    END
    
all:
  BUILD +build
  BUILD +unit-test
  BUILD +integration-test
  BUILD +smoke-test
