FROM hseeberger/scala-sbt:8u265_1.4.0_2.12.12
WORKDIR /scala-example

project-files:
    COPY build.sbt ./
    COPY project project
    # Run sbt for caching purposes.
    RUN touch a.scala && sbt compile && rm a.scala
    SAVE IMAGE

build:
    FROM +project-files
    COPY src src
    RUN sbt compile
    SAVE IMAGE

unit-test:
    FROM +build
    COPY src src
    RUN sbt test

integration-test:
    FROM +build
    COPY src src
    COPY docker-compose.yml ./ 
    WITH DOCKER --compose docker-compose.yml
       RUN sbt it:test
    END

docker:
    FROM +build
    COPY src src
    RUN sbt assembly
    ENTRYPOINT ["java","-cp","target/scala-2.12/scala-example-assembly-1.0.jar","Main"]
    SAVE IMAGE scala-example:latest

smoke-test:
    COPY docker-compose.yml ./ 
    WITH DOCKER \
            --compose docker-compose.yml \
            --load scala-example:latest=+docker
        RUN for i in {1..30}; do nc -z localhost 5432 && break; sleep 1; done; \
            docker run --network=host scala-example:latest
    END
    
all:
  BUILD +build
  BUILD +unit-test
  BUILD +integration-test
  BUILD +smoke-test
