VERSION 0.8

FROM alpine:3.12

WORKDIR /test

PROJECT earthly-technologies/core

test-multiple-on-single-env:
    ENV GOLANG=1.22.2 \
        GO_VERSION=1.22.2 \
    	GOOS=linux \
    	GOARCH=amd64 \
        GO_DOWNLOAD_SHA256=5901c52b7a78002aeff14a21f93e0f064f74ce1360fce51c6ee68cd471216a17

    RUN env
    RUN echo GOLANG=$GOLANG