VERSION 0.8

FROM alpine:3.12

WORKDIR /test

test-multiple-on-single-env:
    ENV VAR1=value1
    ENV VAR2=value2
    ENV VAR3=value3

    RUN env

    RUN test "$VAR1" = "value1"
    RUN test "$VAR2" = "value2"
    RUN test "$VAR3" = "value3"
