IMPORT ./some/local/path AS lib
IMPORT github.com/earthly/hello-world:main  # if alias is not provided, defaults to last element in path (in this case, hello-world)

init:
    DO lib+PRINT --string="Foo Bar"
    COPY lib+PRINT/log.txt ./
    RUN cat log.txt
    BUILD hello-world+hello
