VERSION 0.8
IMPORT ./some/local/path AS lib
IMPORT github.com/earthly/hello-world:main  # if alias is not provided, defaults to last element in path (in this case, hello-world)

build:
    FROM lib+base-image
    DO lib+PRINT --text="IMPORT example"
    COPY lib+get-file/file.txt ./
    RUN cat file.txt
    BUILD hello-world+hello
