VERSION --pass-args 0.7

FROM --pass-args ../..+earthly-integration-test-base

IMPORT .. AS tests

WORKDIR /test

test-all:
    BUILD +test-do-not-track

test-do-not-track:
    HOST api.earthly.dev 127.0.0.1
    ENV DO_NOT_TRACK 1
    COPY api-earthly-stub-server.py /bin/api-earthly-stub-server
    COPY api-earthly-stub-server-shutdown.py /bin/api-earthly-stub-server-shutdown

    # prevent earthly auto-login
    RUN /bin/api-earthly-stub-server && earthly account logout && api-earthly-stub-server-shutdown

    DO --pass-args +RUN_EARTHLY_ARGS --pre_command=/bin/api-earthly-stub-server --post_command=" && api-earthly-stub-server-shutdown" --earthfile=true.earth --target=+true

RUN_EARTHLY_ARGS:
    COMMAND
    ARG earthfile
    ARG target
    ARG should_fail=false
    ARG output_contains
    ARG output_does_not_contain
    ARG pre_command
    ARG post_command
    DO --pass-args tests+RUN_EARTHLY \
        --earthfile=$earthfile \
        --target=$target \
        --should_fail=$should_fail \
        --output_contains=$output_contains \
        --output_does_not_contain=$output_does_not_contain \
        --pre_command=$pre_command \
        --post_command=$post_command \
        --extra_args="--auto-skip --auto-skip-db-path=test.db" \
