name: Earthly Next Docker CI Ubuntu

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/renovate.json5'
      - '.github/CODEOWNERS'
      - 'LICENSE'
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # this job will output a boolean value to check whether files that require these tests to run
  # since all jobs depend on `build-earthly` job, conditionally running it will either cause all jobs to run or skip,
  # depending on the output value of this job
#  check-essential-files:
#    # only run on pull request since push to main is already checking files with paths-ignore
#    if: ${{ github.event_name == 'pull_request' }}
#    uses: ./.github/workflows/reusable-find-pr-changes.yaml
#    permissions:
#      pull-requests: read
#    secrets: inherit
  build-earthly-with-next:
#    needs: check-essential-files
    # allow the job to execute even if check-essential-files is skipped
    if: ${{ !failure() }}
    uses: ./.github/workflows/build-earthly.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      USE_NEXT: true
      SUDO: ""
#      SKIP_JOB: ${{ needs.check-essential-files.outputs.essential-files == 'false' }}
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group1:
    needs: build-earthly-with-next
    if: ${{ !failure() }}
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group1"
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      SKIP_JOB: ${{ needs.build-earthly.result != 'success' }}
      EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group2:
    needs: build-earthly-with-next
    if: ${{ !failure() }}
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group2"
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      SKIP_JOB: ${{ needs.build-earthly.result != 'success' }}
      EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group3:
    needs: build-earthly-with-next
    if: ${{ !failure() }}
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group3"
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      SKIP_JOB: ${{ needs.build-earthly.result != 'success' }}
      EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group4:
    needs: build-earthly-with-next
    if: ${{ !failure() }}
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group4"
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      SKIP_JOB: ${{ needs.build-earthly.result != 'success' }}
      EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group5:
    needs: build-earthly-with-next
    if: ${{ !failure() }}
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group5"
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      SKIP_JOB: ${{ needs.build-earthly.result != 'success' }}
      EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group6:
    needs: build-earthly-with-next
    if: ${{ !failure() }}
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group6"
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      SKIP_JOB: ${{ needs.build-earthly.result != 'success' }}
      EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group7:
    needs: build-earthly-with-next
    if: ${{ !failure() }}
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group7"
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      SKIP_JOB: ${{ needs.build-earthly.result != 'success' }}
      EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group8:
    needs: build-earthly-with-next
    if: ${{ !failure() }}
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group8"
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      SKIP_JOB: ${{ needs.build-earthly.result != 'success' }}
      EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group9:
    needs: build-earthly-with-next
    if: ${{ !failure() }}
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group9"
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      SKIP_JOB: ${{ needs.build-earthly.result != 'success' }}
      EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group10:
    needs: build-earthly-with-next
    if: ${{ !failure() }}
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group10"
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      SKIP_JOB: ${{ needs.build-earthly.result != 'success' }}
      EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group11:
    needs: build-earthly-with-next
    if: ${{ !failure() }}
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group11"
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      SKIP_JOB: ${{ needs.build-earthly.result != 'success' }}
      EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group12:
    needs: build-earthly-with-next
    if: ${{ !failure() }}
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group12"
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      SKIP_JOB: ${{ needs.build-earthly.result != 'success' }}
      EXTRA_ARGS: "--auto-skip"
    secrets: inherit
