# Split into second file just to speed up sequential ci
name: Podman CI Ubuntu 2

on:
  push:
    branches: [ main ]
    paths-ignore: [ docs/** ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ docs/** ]

jobs:
  podman-push-integrations:
    # TODO: Figure out how to run multiple Podman instances in parallel with different ports for buildkitd
    uses: ./.github/workflows/reusable-push-integrations.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      BUILD_EARTHLY_TARGET: "+for-linux"
      RUNS_ON: "ubuntu-latest"
      BINARY: "podman"
      SUDO: "sudo"
    secrets: inherit

  podman-secret-integrations:
    # TODO: Figure out how to run multiple Podman instances in parallel with different ports for buildkitd
    needs: podman-push-integrations
    uses: ./.github/workflows/reusable-secrets-integrations.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      BUILD_EARTHLY_TARGET: "+for-linux"
      RUNS_ON: "ubuntu-latest"
      BINARY: "podman"
      SUDO: "sudo"
    secrets: inherit

  podman-boostrap-integrations:
    # TODO: Figure out how to run multiple Podman instances in parallel with different ports for buildkitd
    needs: podman-secret-integrations
    uses: ./.github/workflows/reusable-bootstrap-integrations.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      BUILD_EARTHLY_TARGET: "+for-linux"
      RUNS_ON: "ubuntu-latest"
      BINARY: "podman"
      SUDO: "sudo"
    secrets: inherit

  podman-repo-auth-tests:
    # TODO: Figure out how to run multiple Podman instances in parallel with different ports for buildkitd
    needs: podman-boostrap-integrations
    uses: ./.github/workflows/reusable-repo-auth-tests.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      BUILD_EARTHLY_TARGET: "+for-linux"
      RUNS_ON: "ubuntu-latest"
      BINARY: "podman"
      SUDO: "sudo"
    secrets: inherit

  podman-export-tests:
    # TODO: Figure out how to run multiple Podman instances in parallel with different ports for buildkitd
    needs: podman-repo-auth-tests
    uses: ./.github/workflows/reusable-export-test.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      BUILD_EARTHLY_TARGET: "+for-linux"
      RUNS_ON: "ubuntu-latest"
      BINARY: "podman"
      SUDO: "sudo"
    secrets: inherit

  podman-misc-tests:
    # TODO: Figure out how to run multiple Podman instances in parallel with different ports for buildkitd
    needs: podman-export-tests
    uses: ./.github/workflows/reusable-misc-tests.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      BUILD_EARTHLY_TARGET: "+for-linux"
      RUNS_ON: "ubuntu-latest"
      BINARY: "podman"
      SUDO: "sudo"
    secrets: inherit
