name: Satellites Docker CI Ubuntu

on:
  push:
    branches: [ main ]
    paths-ignore: [ docs/** ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ docs/** ]

jobs:
  repro-1:
    uses: ./.github/workflows/reuseable-repro-2286.yml
    secrets: inherit
    with:
      FILL_SPACE_GB: 0

  repro-2:
    needs: repro-1
    uses: ./.github/workflows/reuseable-repro-2286.yml
    secrets: inherit
    with:
      FILL_SPACE_GB: 5

  repro-3:
    needs: repro-2
    uses: ./.github/workflows/reuseable-repro-2286.yml
    secrets: inherit
    with:
      FILL_SPACE_GB: 10

  repro-4:
    needs: repro-3
    uses: ./.github/workflows/reuseable-repro-2286.yml
    secrets: inherit
    with:
      FILL_SPACE_GB: 12

  repro-5:
    needs: repro-4
    uses: ./.github/workflows/reuseable-repro-2286.yml
    secrets: inherit
    with:
      FILL_SPACE_GB: 13

  repro-6:
    needs: repro-5
    uses: ./.github/workflows/reuseable-repro-2286.yml
    secrets: inherit
    with:
      FILL_SPACE_GB: 14

  repro-7:
    needs: repro-5
    uses: ./.github/workflows/reuseable-repro-2286.yml
    secrets: inherit
    with:
      FILL_SPACE_GB: 14.5

  repro-8:
    needs: repro-7
    uses: ./.github/workflows/reuseable-repro-2286.yml
    secrets: inherit
    with:
      FILL_SPACE_GB: 15

  repro-9:
    needs: repro-8
    uses: ./.github/workflows/reuseable-repro-2286.yml
    secrets: inherit
    with:
      FILL_SPACE_GB: 20

  repro-10:
    needs: repro-9
    uses: ./.github/workflows/reuseable-repro-2286.yml
    secrets: inherit
    with:
      FILL_SPACE_GB: 100
