name: Docker CI Ubuntu

on:
  push:
    branches: [ main ]
    paths-ignore: [ docs/** ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ docs/** ]

jobs:
  docker-tests:
    uses: ./.github/workflows/reusable-test.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      BUILD_EARTHLY_TARGET: "+for-linux"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
    secrets: inherit

  docker-examples-1:
    uses: ./.github/workflows/reusable-example.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      BUILD_EARTHLY_TARGET: "+for-linux"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      EXAMPLE_NAME: "+examples1"
    secrets: inherit

  docker-examples-2:
    uses: ./.github/workflows/reusable-example.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      BUILD_EARTHLY_TARGET: "+for-linux"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      EXAMPLE_NAME: "+examples2"
    secrets: inherit

  docker-test-local:
    uses: ./.github/workflows/reusable-test-local.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      BUILD_EARTHLY_TARGET: "+for-linux"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
    secrets: inherit

  docker-push-integrations:
    uses: ./.github/workflows/reusable-push-integrations.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      BUILD_EARTHLY_TARGET: "+for-linux"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
    secrets: inherit

  docker-secret-integrations:
    uses: ./.github/workflows/reusable-secret-integrations.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      BUILD_EARTHLY_TARGET: "+for-linux"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
    secrets: inherit

  docker-bootstrap-integrations:
    uses: ./.github/workflows/reusable-bootstrap-integrations.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      BUILD_EARTHLY_TARGET: "+for-linux"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
    secrets: inherit

  docker-repo-auth-tests:
    uses: ./.github/workflows/reusable-repo-auth-tests.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      BUILD_EARTHLY_TARGET: "+for-linux"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
    secrets: inherit

  docker-export-test:
    uses: ./.github/workflows/reusable-export-test.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      BUILD_EARTHLY_TARGET: "+for-linux"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
    secrets: inherit
