name: Podman Examples 1 CI Ubuntu

on:
  push:
    branches: [ main ]
    paths-ignore: [ docs/** ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ docs/** ]

jobs:
  podman-examples-1:
    # TODO: Figure out how to run multiple Podman instances in parallel with different ports for buildkitd
    uses: ./.github/workflows/reusable-example.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      BUILD_EARTHLY_TARGET: "+for-linux"
      RUNS_ON: "ubuntu-latest"
      BINARY: "podman"
      SUDO: "sudo"
      EXAMPLE_NAME: "+examples1"
    secrets: inherit
