# Split into second file just to speed up sequential ci
name: Podman Export Tests CI Ubuntu 2

on:
  push:
    branches: [ main ]
    paths-ignore: [ docs/** ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ docs/** ]

jobs:
  podman-export-tests:
    # TODO: Figure out how to run multiple Podman instances in parallel with different ports for buildkitd
    uses: ./.github/workflows/reusable-export-test.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      BUILD_EARTHLY_TARGET: "+for-linux"
      RUNS_ON: "ubuntu-latest"
      BINARY: "podman"
      SUDO: "sudo"
    secrets: inherit
