name: GitHub Actions CI

on:
  push:
    branches: [ main ]
    paths-ignore: [ docs/** ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ docs/** ]

jobs:
  tests:
    name: +testing-gha-podman
    runs-on: macos-12
    env:
      FORCE_COLOR: 1
    steps:
      - name: Brew version
        run: brew --version


#  build:
#    uses: ./.github/workflows/reuse-ci.yml
#    with:
#      BUILT_EARTHLY_PATH: ./build/darwin/amd64/earthly
#      BUILD_EARTHLY_TARGET: +for-darwin
#    secrets:
#      EARTHLY_INSTALL_ID: ${{ secrets.EARTHLY_INSTALL_ID }}
#      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
#      DOCKERHUB_MIRROR_USERNAME: ${{ secrets.DOCKERHUB_MIRROR_USERNAME }}
#      DOCKERHUB_MIRROR_PASSWORD: ${{ secrets.DOCKERHUB_MIRROR_PASSWORD }}
#    name: Check for binary
#
#  check:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Check for binary
#        run: ls -al ./build/darwin/amd64
