name: Podman CI Ubuntu

on:
  push:
    branches: [ main ]
    paths-ignore: [ docs/** ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ docs/** ]

jobs:
  podman-tests:
    uses: ./.github/workflows/reusable-test.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      BUILD_EARTHLY_TARGET: "+for-linux"
      RUNS_ON: "ubuntu-latest"
      BINARY: "podman"
      SUDO: "sudo"
    secrets: inherit

  podman-examples-1:
    needs: podman-tests
    uses: ./.github/workflows/reusable-example.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      BUILD_EARTHLY_TARGET: "+for-linux"
      RUNS_ON: "ubuntu-latest"
      BINARY: "podman"
      SUDO: "sudo"
      EXAMPLE_NAME: "+examples1"
    secrets: inherit

  podman-examples-2:
    needs: podman-examples-1
    uses: ./.github/workflows/reusable-example.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      BUILD_EARTHLY_TARGET: "+for-linux"
      RUNS_ON: "ubuntu-latest"
      BINARY: "podman"
      SUDO: "sudo"
      EXAMPLE_NAME: "+examples2"
    secrets: inherit

  podman-test-local:
    needs: podman-examples-2
    uses: ./.github/workflows/reusable-test-local.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      BUILD_EARTHLY_TARGET: "+for-linux"
      RUNS_ON: "ubuntu-latest"
      BINARY: "podman"
      SUDO: "sudo"
    secrets: inherit
