name: Secrets Integrations

on:
  workflow_call:
    inputs:
      BUILT_EARTHLY_PATH:
        required: true
        type: string
      BINARY:
        required: true
        type: string
      SUDO:
        type: string
        required: false
      RUNS_ON:
        required: true
        type: string

jobs:
  secret-integration:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ${{inputs.RUNS_ON}}
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: "${{ secrets.EARTHLY_TOKEN }}"
      EARTHLY_INSTALL_ID: "earthly-githubactions"
      DOCKERHUB_MIRROR_USERNAME: "${{ secrets.DOCKERHUB_MIRROR_USERNAME }}"
      DOCKERHUB_MIRROR_PASSWORD: "${{ secrets.DOCKERHUB_MIRROR_PASSWORD }}"
      # Used in our github action as the token - TODO: look to change it into an input
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/stage2-setup
        with:
          DOCKERHUB_MIRROR_USERNAME: "${{ secrets.DOCKERHUB_MIRROR_USERNAME }}"
          DOCKERHUB_MIRROR_PASSWORD: "${{ secrets.DOCKERHUB_MIRROR_PASSWORD }}"
          DOCKERHUB_USERNAME: "${{ secrets.DOCKERHUB_USERNAME }}"
          DOCKERHUB_PASSWORD: "${{ secrets.DOCKERHUB_TOKEN }}"
          EARTHLY_TOKEN: "${{ secrets.EARTHLY_TOKEN }}"
          BUILT_EARTHLY_PATH: "${{ inputs.BUILT_EARTHLY_PATH }}"
          BINARY: "${{ inputs.BINARY }}"
          SUDO: "${{ inputs.SUDO }}"
          USE_SATELLITE: "${{ inputs.USE_SATELLITE }}"
          SATELLITE_NAME: "${{ inputs.SATELLITE_NAME }}"
      - name: Set EARTHLY_VERSION_FLAG_OVERRIDES env
        run: |-
          set -euo pipefail
          EARTHLY_VERSION_FLAG_OVERRIDES="$(tr -d '\n' < .earthly_version_flag_overrides)"
          echo "EARTHLY_VERSION_FLAG_OVERRIDES=$EARTHLY_VERSION_FLAG_OVERRIDES" >> "$GITHUB_ENV"
      - name: install expect
        run: sudo apt-get install -y expect
      - name: run secrets-integration
        run: env earthly=${{inputs.BUILT_EARTHLY_PATH}} scripts/tests/secrets-integration.sh
      - name: Buildkit logs (runs on failure)
        run: ${{inputs.SUDO}} ${{inputs.BINARY}} logs earthly-buildkitd || true
        if: ${{ failure() }}
